export const CANONICAL_BRANDS = [
  "General Motors",
  "Bosch",
  "Patron",
  "Gates",
  "Delphi",
  "Sangsin",
  "Elring",
  "Kolbenschmidt",
  "Miles",
  "Lynx",
  "Vernet",
  "Uxclent",
  "Stellox",
  "Big Filter",
  "Filtron",
  "Mahle",
  "Mann",
  "Dello",
  "Airtex",
  "JP Group",
  "Dolz",
  "Cargen",
  "Seinsa",
  "Hengst",
  "NGK",
  "TRW",
  "INA",
  "HSB",
  "ERA",
  "UFI",
  "VIKA",
  "KS",
  "ICER",
  "CTR",
  "RTS",
  "FEBEST",
  "FAG",
  "SWAG",
] as const;

const BRAND_MAP: Record<string, string> = {
  "GENERAL MOTORS": "General Motors",
  "GM OE": "General Motors",
  GM: "General Motors",
  BOSCH: "Bosch",
  PATRON: "Patron",
  GATES: "Gates",
  DELPHI: "Delphi",
  DELLO: "Dello",
  LYNX: "Lynx",
  "BIG FILTER": "Big Filter",
  FILTRON: "Filtron",
  MAHLE: "Mahle",
  MANN: "Mann",
  STELLOX: "Stellox",
  AIRTEX: "Airtex",
  SANGSIN: "Sangsin",
  SANGSIN_BRAKE: "Sangsin",
  ELRING: "Elring",
  KOLBENSCHMIDT: "Kolbenschmidt",
  MILES: "Miles",
  TESLA: "Tesla",
  "JP GROUP": "JP Group",
  DOLZ: "Dolz",
  CARGEN: "Cargen",
  VERNET: "Vernet",
  UXCLENT: "Uxclent",
  SEINSA: "Seinsa",
  HENGST: "Hengst",
  "PSA OE": "PSA",
};

export function canonicalizeBrand(value: string): string {
  const trimmed = value.trim().replace(/\s+/g, " ");
  if (!trimmed) return "";

  const upper = trimmed.toUpperCase();
  return BRAND_MAP[upper] ?? trimmed;
}
